databases:
  - name: medvault
    databaseName: medvault
    user: medvault

services:
  - type: web
    name: medvault
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn medvault_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medvault
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4